//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manga_Web.Translations.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manga_Web.Translations.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin toegankelijkheden.
        /// </summary>
        public static string Admin_toegankelijkheden {
            get {
                return ResourceManager.GetString("Admin toegankelijkheden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteurs.
        /// </summary>
        public static string Auteurs {
            get {
                return ResourceManager.GetString("Auteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logs.
        /// </summary>
        public static string Error_logs {
            get {
                return ResourceManager.GetString("Error logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers beheer.
        /// </summary>
        public static string Gebruikers_beheer {
            get {
                return ResourceManager.GetString("Gebruikers beheer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga Boeken.
        /// </summary>
        public static string Manga_Boeken {
            get {
                return ResourceManager.GetString("Manga Boeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuws.
        /// </summary>
        public static string Nieuws {
            get {
                return ResourceManager.GetString("Nieuws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkennen.
        /// </summary>
        public static string Verkennen {
            get {
                return ResourceManager.GetString("Verkennen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg boek toe.
        /// </summary>
        public static string Voeg_boek_toe {
            get {
                return ResourceManager.GetString("Voeg boek toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg genre toe.
        /// </summary>
        public static string Voeg_genre_toe {
            get {
                return ResourceManager.GetString("Voeg genre toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg nieuwe....
        /// </summary>
        public static string Voeg_nieuwe___ {
            get {
                return ResourceManager.GetString("Voeg nieuwe...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg nieuwe auteurs toe.
        /// </summary>
        public static string Voeg_nieuwe_auteurs_toe {
            get {
                return ResourceManager.GetString("Voeg nieuwe auteurs toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg nieuwsbericht toe.
        /// </summary>
        public static string Voeg_nieuwsbericht_toe {
            get {
                return ResourceManager.GetString("Voeg nieuwsbericht toe", resourceCulture);
            }
        }
    }
}
