// <auto-generated />
namespace MangaBook_Models.Resources.Models {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Author {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Author() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaBook_Models.Resources.Models.Author", typeof(Author).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string geboorteDatum {
            get {
                return ResourceManager.GetString("geboorteDatum", resourceCulture);
            }
        }
        
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        public static string favoriteFood {
            get {
                return ResourceManager.GetString("favoriteFood", resourceCulture);
            }
        }
        
        public static string Nationaliteit {
            get {
                return ResourceManager.GetString("Nationaliteit", resourceCulture);
            }
        }
        
        public static string FavorieteSport {
            get {
                return ResourceManager.GetString("FavorieteSport", resourceCulture);
            }
        }
    }
}
